// Code generated by github.com/virzz/structx. DO NOT EDIT.

package example

func (s *Config) WithInner(v string) { s.inner = v }

func (s *Config) WithArraySubConfig(v []SubConfig)             { s.ArraySubConfig = v }
func (s *Config) WithMapStruct(v map[string]struct{})          { s.MapStruct = v }
func (s *Config) WithSubStar(v *SubConfig)                     { s.SubStar = v }
func (s *Config) WithAAA(v string)                             { s.AAA = v }
func (s *Config) WithMapSubConfig(v map[string]SubConfig)      { s.MapSubConfig = v }
func (s *Config) WithSub(v SubConfig)                          { s.Sub = v }
func (s *Config) WithPort(v int)                               { s.Port = v }
func (s *Config) WithMapStar(v map[string]*string)             { s.MapStar = v }
func (s *Config) WithArray(v []string)                         { s.Array = v }
func (s *Config) WithArrayStruct(v []struct{})                 { s.ArrayStruct = v }
func (s *Config) WithMap(v map[string]string)                  { s.Map = v }
func (s *Config) WithAddr(v string)                            { s.Addr = v }
func (s *Config) WithDebug(v bool)                             { s.Debug = v }
func (s *Config) WithPtr(v *string)                            { s.Ptr = v }
func (s *Config) WithArraySubConfigStar(v []*SubConfig)        { s.ArraySubConfigStar = v }
func (s *Config) WithMapSubConfigStar(v map[string]*SubConfig) { s.MapSubConfigStar = v }
func (s *Config) WithArrayStar(v []*string)                    { s.ArrayStar = v }
func (s *Config) WithBBB(v string)                             { s.BBB = v }
